install.packages("tidyverse")
install.packages("synthesis")
install.packages("fdm2id")
install.packages("dirichletprocess")
install.packages("concaveman")
install.packages("grid")
install.packages("gridExtra")
install.packages("plyr")
install.packages("salso")
install.packages("mcclust")
install.packages("mcclust.ext")
install.packages("dbscan")

install.packages("devtools")
devtools::install_github("shounakchattopadhyay/NN-DM")
devtools::install_github("MaStatLab/PTT")
